-- MySQL Script generated by MySQL Workbench
-- Mon Dec  3 19:30:40 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Company_Listings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Company_Listings` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Company_Listings` (
  `Company_Id` INT NOT NULL,
  `Title_Of_Job` VARCHAR(45) NULL,
  `Type_Of_Job` VARCHAR(45) NULL,
  `Location` VARCHAR(45) NULL,
  `Date Posted` DATETIME NULL,
  PRIMARY KEY (`Company_Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`University`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`University` ;

CREATE TABLE IF NOT EXISTS `mydb`.`University` (
  `University_Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Location` VARCHAR(45) NULL,
  PRIMARY KEY (`University_Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `Student_Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Major` VARCHAR(45) NULL,
  `Year` INT NULL,
  `Company_Listings_Company_Id` INT NOT NULL,
  `University_University_Id` INT NOT NULL,
  PRIMARY KEY (`Student_Id`),
  INDEX `fk_Student_Company_Listings_idx` (`Company_Listings_Company_Id` ASC),
  INDEX `fk_Student_University1_idx` (`University_University_Id` ASC),
  CONSTRAINT `fk_Student_Company_Listings`
    FOREIGN KEY (`Company_Listings_Company_Id`)
    REFERENCES `mydb`.`Company_Listings` (`Company_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_University1`
    FOREIGN KEY (`University_University_Id`)
    REFERENCES `mydb`.`University` (`University_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Links`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Links` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Links` (
  `Link_Id` INT NOT NULL,
  `Link` VARCHAR(45) NULL,
  PRIMARY KEY (`Link_Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Resources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Resources` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Resources` (
  `Resource_Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Type_Of_Resource` VARCHAR(45) NULL,
  `Links_Link_Id` INT NOT NULL,
  PRIMARY KEY (`Resource_Id`),
  INDEX `fk_Resources_Links1_idx` (`Links_Link_Id` ASC),
  CONSTRAINT `fk_Resources_Links1`
    FOREIGN KEY (`Links_Link_Id`)
    REFERENCES `mydb`.`Links` (`Link_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
